INSERT Product(ProductName,Price) VALUES('Chai',18)
INSERT Product(ProductName,Price) VALUES('Chang',19)
INSERT Product(ProductName,Price) VALUES('Aniseed Syrup',19)
INSERT Product(ProductName,Price) VALUES('Chef Anton''s Cajun Seasoning',2)
INSERT Product(ProductName,Price) VALUES('Chef Anton''s Gumbo Mix',21)
INSERT Product(ProductName,Price) VALUES('Grandma''s Boysenberry Spread',25)
INSERT Product(ProductName,Price) VALUES('Uncle Bob''s Organic Dried Pears',30)
INSERT Product(ProductName,Price) VALUES('Northwoods Cranberry Sauce',40)
INSERT Product(ProductName,Price) VALUES('Mishi Kobe Niku',97)
INSERT Product(ProductName,Price) VALUES('Ikura',31)
INSERT Product(ProductName,Price) VALUES('Queso Cabrales',21)
INSERT Product(ProductName,Price) VALUES('Queso Manchego La Pastora',38)
INSERT Product(ProductName,Price) VALUES('Konbu',6)
INSERT Product(ProductName,Price) VALUES('Tofu',23)
INSERT Product(ProductName,Price) VALUES('Genen Shouyu',15)
INSERT Product(ProductName,Price) VALUES('Pavlova',17)
INSERT Product(ProductName,Price) VALUES('Alice Mutton',39)
INSERT Product(ProductName,Price) VALUES('Carnarvon Tigers',62)
INSERT Product(ProductName,Price) VALUES('Teatime Chocolate Biscuits',9)
INSERT Product(ProductName,Price) VALUES('Sir Rodney''s Marmalade',81)
INSERT Product(ProductName,Price) VALUES('Sir Rodney''s Scones',10)
INSERT Product(ProductName,Price) VALUES('Gustaf''s Knäckebröd',21)
INSERT Product(ProductName,Price) VALUES('Tunnbröd',9)
INSERT Product(ProductName,Price) VALUES('Guaraná Fantástica',4)
INSERT Product(ProductName,Price) VALUES('NuNuCa Nuß-Nougat-Creme',14)
INSERT Product(ProductName,Price) VALUES('Gumbär Gummibärchen',31)
INSERT Product(ProductName,Price) VALUES('Schoggi Schokolade',43)
INSERT Product(ProductName,Price) VALUES('Rössle Sauerkraut',45)
INSERT Product(ProductName,Price) VALUES('Thüringer Rostbratwurst',123)
INSERT Product(ProductName,Price) VALUES('Nord-Ost Matjeshering',25)
INSERT Product(ProductName,Price) VALUES('Gorgonzola Telino',12)
INSERT Product(ProductName,Price) VALUES('Mascarpone Fabioli',32)
INSERT Product(ProductName,Price) VALUES('Geitost',2)
INSERT Product(ProductName,Price) VALUES('Sasquatch Ale',14)
INSERT Product(ProductName,Price) VALUES('Steeleye Stout',18)
INSERT Product(ProductName,Price) VALUES('Inlagd Sill',19)
INSERT Product(ProductName,Price) VALUES('Gravad lax',26)
INSERT Product(ProductName,Price) VALUES('Côte de Blaye',263)
INSERT Product(ProductName,Price) VALUES('Chartreuse verte',18)
INSERT Product(ProductName,Price) VALUES('Boston Crab Meat',19)
INSERT Product(ProductName,Price) VALUES('Jack''s New England Clam Chowder',19)
INSERT Product(ProductName,Price) VALUES('Singaporean Hokkien Fried Mee',14)
INSERT Product(ProductName,Price) VALUES('Ipoh Coffee',46)
INSERT Product(ProductName,Price) VALUES('Gula Malacca',19)
INSERT Product(ProductName,Price) VALUES('Rogede sild',9)
INSERT Product(ProductName,Price) VALUES('Spegesild',12)
INSERT Product(ProductName,Price) VALUES('Zaanse koeken',9)
INSERT Product(ProductName,Price) VALUES('Chocolade',12)
INSERT Product(ProductName,Price) VALUES('Maxilaku',20)
INSERT Product(ProductName,Price) VALUES('Valkoinen suklaa',16)
INSERT Product(ProductName,Price) VALUES('Manjimup Dried Apples',53)
INSERT Product(ProductName,Price) VALUES('Filo Mix',7)
INSERT Product(ProductName,Price) VALUES('Perth Pasties',32)
INSERT Product(ProductName,Price) VALUES('Tourtière',7)
INSERT Product(ProductName,Price) VALUES('Pâté chinois',24)
INSERT Product(ProductName,Price) VALUES('Gnocchi di nonna Alice',38)
INSERT Product(ProductName,Price) VALUES('Ravioli Angelo',19)
INSERT Product(ProductName,Price) VALUES('Escargots de Bourgogne',13)
INSERT Product(ProductName,Price) VALUES('Raclette Courdavault',55)
INSERT Product(ProductName,Price) VALUES('Camembert Pierrot',34)
INSERT Product(ProductName,Price) VALUES('Sirop d''érable',28.5)
INSERT Product(ProductName,Price) VALUES('Tarte au sucre',49)
INSERT Product(ProductName,Price) VALUES('Vegie-spread',43)
INSERT Product(ProductName,Price) VALUES('Wimmers gute Semmelknödel',33.25)
INSERT Product(ProductName,Price) VALUES('Louisiana Fiery Hot Pepper Sauce',21.05)
INSERT Product(ProductName,Price) VALUES('Louisiana Hot Spiced Okra',17)
INSERT Product(ProductName,Price) VALUES('Laughing Lumberjack Lager',14)
INSERT Product(ProductName,Price) VALUES('Scottish Longbreads',12.5)
INSERT Product(ProductName,Price) VALUES('Gudbrandsdalsost',36)
INSERT Product(ProductName,Price) VALUES('Outback Lager',15)
INSERT Product(ProductName,Price) VALUES('Flotemysost',21.5)
INSERT Product(ProductName,Price) VALUES('Mozzarella di Giovanni',34.8)
INSERT Product(ProductName,Price) VALUES('Röd Kaviar',15)
INSERT Product(ProductName,Price) VALUES('Longlife Tofu',10)
INSERT Product(ProductName,Price) VALUES('Rhönbräu Klosterbier',7.75)
INSERT Product(ProductName,Price) VALUES('Lakkalikööri',18)
INSERT Product(ProductName,Price) VALUES('Original Frankfurter grüne Soßer',12)

INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('ALFKI','Alfreds Futterkiste')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('ANATR','Ana Trujillo Emparedados y helados')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('ANTON','Antonio Moreno Taquería')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('AROUT','Around the Horn')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('BERGS','Berglunds snabbköp')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('BLAUS','Blauer See Delikatessen')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('BLONP','Blondesddsl père et fils')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('BOLID','Bólido Comidas preparadas')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('BLONP','Blondesddsl père et fils')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('BOTTM','Bottom-Dollar Markets')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('BSBEV','B''s Beverages')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('CACTU','Cactus Comidas para llevar')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('CENTC','Centro comercial Moctezuma')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('CHOPS','Chop-suey Chinese')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('COMMI','Comércio Mineiro')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('CONSH','Consolidated Holdings')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('DRACD','Drachenblut Delikatessen')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('DUMON','Du monde entier')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('EASTC','Eastern Connection')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('ERNSH','Ernst Handel')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('FAMIA','Familia Arquibaldo')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('FISSA','FISSA Fabrica Inter. Salchichas S.A.')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('FOLIG','Folies gourmandes')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('FOLKO','Folk och fä HB')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('FRANK','Frankenversand')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('FRANR','France restauration')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('FRANS','Franchi S.p.A.')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('FURIB','Furia Bacalhau e Frutos do Mar')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('GALED','Galería del gastrónomo')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('GODOS','Godos Cocina Típica')
iNSERT INTO Customer(CustomerCode, CustomerName) VALUES ('GOURL','Gourmet Lanchonetes')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('GREAL','Great Lakes Food Market')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('GROSR','GROSELLA-Restaurante')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('HANAR','Hanari Carnes')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('HILAA','HILARION-Abastos')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('HUNGC','Hungry Coyote Import Store')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('HUNGO','Hungry Owl All-Night Grocers')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('ISLAT','Island Trading')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('KOENE','Königlich Essen')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('LACOR','La corne d''abondance')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('LAMAI','La maison d''Asie')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('LAUGB','Laughing Bacchus Wine Cellars')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('LAZYK','Lazy K Kountry Store')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('LEHMS','Lehmanns Marktstand')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('LETSS','Let''s Stop N Shop')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('LILAS','LILA-Supermercado')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('LINOD','LINO-Delicateses')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('LONEP','Lonesome Pine Restaurant')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('MAGAA','Magazzini Alimentari Riuniti')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('MAISD','Maison Dewey')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('MEREP','Mère Paillarde')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('MORGK','Morgenstern Gesundkost')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('NORTS','North/South')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('OCEAN','Océano Atlántico Ltda.')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('OLDWO','Old World Delicatessen')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('OTTIK','Ottilies Käseladen')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('PARIS','Paris spécialités')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('PERIC','Pericles Comidas clásicas')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('PICCO','Piccolo und mehr')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('PRINI','Princesa Isabel Vinhos')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('QUEDE','Que Delícia')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('QUEEN','Queen Cozinha')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('QUICK','QUICK-Stop')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('RANCH','Rancho grande')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('RATTC','Rattlesnake Canyon Grocery')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('REGGC','Reggiani Caseifici')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('RICAR','Ricardo Adocicados')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('RICSU','Richter Supermarkt')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('ROMEY','Romero y tomillo')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('SANTG','Santé Gourmet')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('SAVEA','Save-a-lot Markets')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('SEVES','Seven Seas Imports')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('SIMOB','Simons bistro')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('SPECD','Spécialités du monde')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('SPLIR','Split Rail Beer & Ale')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('SUPRD','Suprêmes délices')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('THEBI','The Big Cheese')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('THECR','The Cracker Box')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('TOMSP','Toms Spezialitäten')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('TORTU','Tortuga Restaurante')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('TRADH','Tradição Hipermercados')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('TRAIH','Trail''s Head Gourmet Provisioners')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('VAFFE','Vaffeljernet')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('VICTE','Victuailles en stock')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('VINET','Vins et alcools Chevalier')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('WANDK','Die Wandernde Kuh')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('WARTH','Wartian Herkku')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('WELLI','Wellington Importadora')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('WHITC','White Clover Markets')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('WILMK','Wilman Kala')
INSERT INTO Customer(CustomerCode, CustomerName) VALUES ('WOLZA','Wolski  Zajazd')
